### ISSUE TITLE
`permits if:`

### ISSUE THREAD

**Issue by vendethiel** [asakusarb/action_args#7]
Would you be okay with adding an `if` option to `permits`? (and maybe unless)
(not sure how rails handles duplication on that side)

**Comment by vendethiel** [comment]
hi @amatsuda , are you interested in such a feature?

**Comment by amatsuda** [comment]
TBH I've never hit a need for those options, but PRs are always welcomed :)

**Comment by vendethiel** [comment]
well, it's useful if you have different attributes allowed for different users.

Maybe this is actually just trying to reinvent some kind of authorization system here... Good thing is that action_args works well with cancan :+1:
